### ISSUE TITLE
Please don't store private_keys in the source files

### ISSUE THREAD

**Issue by markkovari** [lxndrvn/lemezpolc#2]
Use system environments like:
https://stackoverflow.com/questions/4906977/access-environment-variables-from-python

**Comment by doriczapari** [comment]
Hi @markkovari ,
I'm Dori, Szandra's mentor on this project. Thanks for opening the issue, although I find it a bit problematic. First of all, it's not really helpful, as you didn't point to the keys you're talking about in the code, so we're not sure where to look. Also, the wording is a little odd - "Please don't do X" sounds really condescending if you're commenting on someone's private project, especially if they didn't ask you for help or mentoring directly. Maybe you didn't mean this in a bad way at all, but next time if you have a comment like that maybe just go for a neutral "Private keys are stored in source files", link the code in the description and add your own explanation before linking a StackOverflow question, it helps a lot more.

I hope this feedback doesn't rub you in the wrong way - I find communication extremely important, especially when helping beginners. I think it's worth examining what can be done better, how can you communicate with more empathy - here's a great resource discussing the "tone problem" in tech: https://compassionatecoding.com/blog/2016/8/25/tech-has-a-toxic-tone-problemlets-fix-it

Thanks again for opening the issue, please get back to us if you have more info to add about the private keys or anything else you find :)

**Comment by markkovari** [comment]
You are totally right, I was on the tram when the issue was created, I just don't want let others to @lxndrvn secret_keys to APIs.
